language: php
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  fast_finish: true
  include:
  - php: '7.2'
    env:
    - EXECUTE_DEPLOYMENT=true
  - php: master
  allow_failures:
  - php: master
before_install:
- phpenv config-rm xdebug.ini || true
install:
- composer install --no-interaction --no-progress --no-suggest --prefer-dist
script:
- vendor/bin/box compile
notifications:
  email: true
deploy:
  provider: releases
  api_key:
    secure: qAdMxKy3yXhfc81vTt9ubcQgl3L3Op9NCaYm9I8lSY3KHdE39hV2bAT2jhfbC+bnJ+NvPRiCqWqoN0jfssTDJvJuz4fK69MxtQLDtBNG/ffpbuwruY4beN1PyiJ7vdCzJ+SWwu2VPCmhXcvf5IUT3JH4otd/AKfkz24rx7mhsOqyw6ppFfzyQOpAwvmPppkg0UKFUKEgv1ECSWDaljhTs6ReD1ztbMZRwLpY0a8VAxHn0MejvdM/hD2Y8nMUc6r2cS4G+ykRFtxk2qunc9T62PLhp3B71QNNC3UqiY4QgAIl0evDWMBlAI3NUp6Z3nzcGYK/+4GZQ54hzioo17RPdcgpCWJ0fOBieKdyPQZIgNKYxu/bK0ErVHwa914+or6F2t/ULn/mEoIcs9Ixh2jYLjvI4EWYGe44KuD1g21n462GPYFRRkqXQz1wNoMfbkKCZiAl+l5XLLZOpnXHzVYf3ng1eyiU7m4+Ao+faIFhOZyjbuJv+wswXEqMttLfzpyxPUvL0l58JSk/r82xc7geXDhUON01MAcA1HA9diWIYd7GogTdZeTiXpOP63si7q+1r7zc6ocImTXaH4xr8WzkzmBoGchSGYHgbTAWXpLvDUTokRJimYYowMg2JQVECB3s9jY/LfKp823NBATLN6APi1Wo89oWuQixeaCdmxo4QT0=
  file: bin/exif2geojson.phar
  skip_cleanup: true
  on:
    repo: lgndhq/exif2geojson
    tags: true
