language: php
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  fast_finish: true
  include:
  - php: '7.2'
    env:
    - EXECUTE_DEPLOYMENT=true
  - php: master
  allow_failures:
  - php: master
before_install:
  - phpenv config-rm xdebug.ini || true
install:
- composer install --no-interaction --no-progress --no-suggest --prefer-dist
script:
- vendor/bin/box build  # Build your PHAR
notifications:
  email: true
